### ISSUE TITLE
Recommendation:  Tag Current Master With "v1"

### ISSUE THREAD

**Issue by lupinia** [kjatar/RelayControllers#1]
Just a suggestion, but adding a "v1" tag to the current `master` commit (https://github.com/kjatar/RelayControllers/commit/6e1857dd8e4de5284fd00e5176c2967e95c1aa1b) will help make it easier to reference and keep track of major milestones as we work on future updates together :)

**Comment by kjatar** [comment]
Could not reproduce. =P
